use_frameworks!

platform :ios, '8.0'

target 'GYEasyForm_Example' do
  pod 'GYEasyForm', :path => '../'
  pod 'GYEasyForm/Rows', :path => '../'

  target 'GYEasyForm_Tests' do
    inherit! :search_paths

    
  end
end
